test newman

diff --git a/.github/workflows/test_newman.yaml b/.github/workflows/test_newman.yaml
--- a/.github/workflows/test_newman.yaml
+++ b/.github/workflows/test_newman.yaml
@@ -38,7 +38,10 @@ jobs:
       - name: Run Postman Collection
         run: |
           newman run postmanCollections/sample-collection.postman_collection.json  
-        # continue-on-error: true        
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Error: Newman run command failed with exit code $exit_code"
+          fi  
 
       - name: Proceed with subsequent steps 
         if: always()       
